<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\FloridaCity;
use Illuminate\Database\Seeder;

class FloridaCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::where('state_id','3930')->delete();
        City::insert([
            ["state_id"=>"3930", "status"=> "active","name"=>"Alachua"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Altamonte Springs"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Anna Maria"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Apalachicola"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Apopka"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Atlantic Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Auburndale"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Aventura"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Avon Park"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Bal Harbour"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Bartow"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Bay Harbor Islands"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Boca Raton"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Bonita Springs"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Boynton Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Bradenton"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Brooksville"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Cape Canaveral"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Cape Coral"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Casselberry"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Celebration"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Chipley"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Cinco Bayou"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Clearwater"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Clermont"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Clewiston"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Cocoa"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Cocoa Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Coconut Creek"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Coral Gables"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Coral Springs"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Crystal River"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Dania Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Davie"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Daytona Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Deerfield Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"DeFuniak Springs"],
            ["state_id"=>"3930", "status"=> "active","name"=>"DeLand"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Delray Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Deltona"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Destin"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Dunedin"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Eagle Lake"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Edgewater"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Edgewood"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Eustis"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Fort Lauderdale"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Fort Meade"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Fort Myers"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Fort Myers Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Fort Pierce"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Fort Walton Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Fruitland Park"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Gainesville"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Greenacres"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Green Cove Springs"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Gulf Breeze"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Gulfport"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Haines City"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Hallandale Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Hawthorne"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Hialeah"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Hialeah Gardens"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Highland Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Hollywood"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Holly Hill"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Holmes Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Homestead"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Hypoluxo"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Indialantic"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Jacksonville"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Juno Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Jupiter"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Key Biscayne"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Key West"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Kissimmee"],
            ["state_id"=>"3930", "status"=> "active","name"=>"LaBelle"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Lady Lake"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Lake Alfred"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Lakeland"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Lake Mary"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Lake Park"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Lake Wales"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Lake Worth"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Lantana"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Largo"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Lauderdale By The Sea"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Lauderhill"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Leesburg"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Lighthouse Point"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Longboat Key"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Longwood"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Maitland"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Marco Island"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Margate"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Melbourne"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Melbourne Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Miami"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Miami Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Milton"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Minneola"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Miramar"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Mount Dora"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Naples"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Neptune Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"New Port Richey"],
            ["state_id"=>"3930", "status"=> "active","name"=>"New Smyrna Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Niceville"],
            ["state_id"=>"3930", "status"=> "active","name"=>"North Miami"],
            ["state_id"=>"3930", "status"=> "active","name"=>"North Miami Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"North Port"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Oakland Park"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Ocala"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Ocean Ridge"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Ocoee"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Okeechobee"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Oldsmar"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Orange Park"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Orlando"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Ormond Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Oviedo"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Palatka"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Palm Bay"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Palm Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Palm Beach Gardens"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Palm Coast"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Palmetto"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Panama City"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Panama City Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Pembroke Pines"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Pensacola"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Pinecrest"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Pinellas Park"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Plant City"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Plantation"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Pompano Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Ponce Inlet"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Port Orange"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Port St. Lucie"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Punta Gorda"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Rockledge"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Royal Palm Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"St. Augustine"],
            ["state_id"=>"3930", "status"=> "active","name"=>"St. Augustine Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"St. Cloud"],
            ["state_id"=>"3930", "status"=> "active","name"=>"St. Pete Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"St. Petersburg"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Safety Harbor"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Sanford"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Sanibel"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Sarasota"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Satellite Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Seaside"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Sebastian"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Sewall's Point"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Shalimar"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Stuart"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Surfside"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Tallahassee"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Tamarac"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Tampa"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Tarpon Springs"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Tavares"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Temple Terrace"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Titusville"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Treasure Island"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Valparaiso"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Venice"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Vero Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Wellington"],
            ["state_id"=>"3930", "status"=> "active","name"=>"West Melbourne"],
            ["state_id"=>"3930", "status"=> "active","name"=>"West Palm Beach"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Weston"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Wilton Manors"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Winter Garden"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Winter Haven"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Winter Park"],
            ["state_id"=>"3930", "status"=> "active","name"=>"Winter Springs"],
        ]);
        FloridaCity::insert([
            ["name"=>"Alachua"],
            ["name"=>"Altamonte Springs"],
            ["name"=>"Anna Maria"],
            ["name"=>"Apalachicola"],
            ["name"=>"Apopka"],
            ["name"=>"Atlantic Beach"],
            ["name"=>"Auburndale"],
            ["name"=>"Aventura"],
            ["name"=>"Avon Park"],
            ["name"=>"Bal Harbour"],
            ["name"=>"Bartow"],
            ["name"=>"Bay Harbor Islands"],
            ["name"=>"Boca Raton"],
            ["name"=>"Bonita Springs"],
            ["name"=>"Boynton Beach"],
            ["name"=>"Bradenton"],
            ["name"=>"Brooksville"],
            ["name"=>"Cape Canaveral"],
            ["name"=>"Cape Coral"],
            ["name"=>"Casselberry"],
            ["name"=>"Celebration"],
            ["name"=>"Chipley"],
            ["name"=>"Cinco Bayou"],
            ["name"=>"Clearwater"],
            ["name"=>"Clermont"],
            ["name"=>"Clewiston"],
            ["name"=>"Cocoa"],
            ["name"=>"Cocoa Beach"],
            ["name"=>"Coconut Creek"],
            ["name"=>"Coral Gables"],
            ["name"=>"Coral Springs"],
            ["name"=>"Crystal River"],
            ["name"=>"Dania Beach"],
            ["name"=>"Davie"],
            ["name"=>"Daytona Beach"],
            ["name"=>"Deerfield Beach"],
            ["name"=>"DeFuniak Springs"],
            ["name"=>"DeLand"],
            ["name"=>"Delray Beach"],
            ["name"=>"Deltona"],
            ["name"=>"Destin"],
            ["name"=>"Dunedin"],
            ["name"=>"Eagle Lake"],
            ["name"=>"Edgewater"],
            ["name"=>"Edgewood"],
            ["name"=>"Eustis"],
            ["name"=>"Fort Lauderdale"],
            ["name"=>"Fort Meade"],
            ["name"=>"Fort Myers"],
            ["name"=>"Fort Myers Beach"],
            ["name"=>"Fort Pierce"],
            ["name"=>"Fort Walton Beach"],
            ["name"=>"Fruitland Park"],
            ["name"=>"Gainesville"],
            ["name"=>"Greenacres"],
            ["name"=>"Green Cove Springs"],
            ["name"=>"Gulf Breeze"],
            ["name"=>"Gulfport"],
            ["name"=>"Haines City"],
            ["name"=>"Hallandale Beach"],
            ["name"=>"Hawthorne"],
            ["name"=>"Hialeah"],
            ["name"=>"Hialeah Gardens"],
            ["name"=>"Highland Beach"],
            ["name"=>"Hollywood"],
            ["name"=>"Holly Hill"],
            ["name"=>"Holmes Beach"],
            ["name"=>"Homestead"],
            ["name"=>"Hypoluxo"],
            ["name"=>"Indialantic"],
            ["name"=>"Jacksonville"],
            ["name"=>"Juno Beach"],
            ["name"=>"Jupiter"],
            ["name"=>"Key Biscayne"],
            ["name"=>"Key West"],
            ["name"=>"Kissimmee"],
            ["name"=>"LaBelle"],
            ["name"=>"Lady Lake"],
            ["name"=>"Lake Alfred"],
            ["name"=>"Lakeland"],
            ["name"=>"Lake Mary"],
            ["name"=>"Lake Park"],
            ["name"=>"Lake Wales"],
            ["name"=>"Lake Worth"],
            ["name"=>"Lantana"],
            ["name"=>"Largo"],
            ["name"=>"Lauderdale By The Sea"],
            ["name"=>"Lauderhill"],
            ["name"=>"Leesburg"],
            ["name"=>"Lighthouse Point"],
            ["name"=>"Longboat Key"],
            ["name"=>"Longwood"],
            ["name"=>"Maitland"],
            ["name"=>"Marco Island"],
            ["name"=>"Margate"],
            ["name"=>"Melbourne"],
            ["name"=>"Melbourne Beach"],
            ["name"=>"Miami"],
            ["name"=>"Miami Beach"],
            ["name"=>"Milton"],
            ["name"=>"Minneola"],
            ["name"=>"Miramar"],
            ["name"=>"Mount Dora"],
            ["name"=>"Naples"],
            ["name"=>"Neptune Beach"],
            ["name"=>"New Port Richey"],
            ["name"=>"New Smyrna Beach"],
            ["name"=>"Niceville"],
            ["name"=>"North Miami"],
            ["name"=>"North Miami Beach"],
            ["name"=>"North Port"],
            ["name"=>"Oakland Park"],
            ["name"=>"Ocala"],
            ["name"=>"Ocean Ridge"],
            ["name"=>"Ocoee"],
            ["name"=>"Okeechobee"],
            ["name"=>"Oldsmar"],
            ["name"=>"Orange Park"],
            ["name"=>"Orlando"],
            ["name"=>"Ormond Beach"],
            ["name"=>"Oviedo"],
            ["name"=>"Palatka"],
            ["name"=>"Palm Bay"],
            ["name"=>"Palm Beach"],
            ["name"=>"Palm Beach Gardens"],
            ["name"=>"Palm Coast"],
            ["name"=>"Palmetto"],
            ["name"=>"Panama City"],
            ["name"=>"Panama City Beach"],
            ["name"=>"Pembroke Pines"],
            ["name"=>"Pensacola"],
            ["name"=>"Pinecrest"],
            ["name"=>"Pinellas Park"],
            ["name"=>"Plant City"],
            ["name"=>"Plantation"],
            ["name"=>"Pompano Beach"],
            ["name"=>"Ponce Inlet"],
            ["name"=>"Port Orange"],
            ["name"=>"Port St. Lucie"],
            ["name"=>"Punta Gorda"],
            ["name"=>"Rockledge"],
            ["name"=>"Royal Palm Beach"],
            ["name"=>"St. Augustine"],
            ["name"=>"St. Augustine Beach"],
            ["name"=>"St. Cloud"],
            ["name"=>"St. Pete Beach"],
            ["name"=>"St. Petersburg"],
            ["name"=>"Safety Harbor"],
            ["name"=>"Sanford"],
            ["name"=>"Sanibel"],
            ["name"=>"Sarasota"],
            ["name"=>"Satellite Beach"],
            ["name"=>"Seaside"],
            ["name"=>"Sebastian"],
            ["name"=>"Sewall's Point"],
            ["name"=>"Shalimar"],
            ["name"=>"Stuart"],
            ["name"=>"Surfside"],
            ["name"=>"Tallahassee"],
            ["name"=>"Tamarac"],
            ["name"=>"Tampa"],
            ["name"=>"Tarpon Springs"],
            ["name"=>"Tavares"],
            ["name"=>"Temple Terrace"],
            ["name"=>"Titusville"],
            ["name"=>"Treasure Island"],
            ["name"=>"Valparaiso"],
            ["name"=>"Venice"],
            ["name"=>"Vero Beach"],
            ["name"=>"Wellington"],
            ["name"=>"West Melbourne"],
            ["name"=>"West Palm Beach"],
            ["name"=>"Weston"],
            ["name"=>"Wilton Manors"],
            ["name"=>"Winter Garden"],
            ["name"=>"Winter Haven"],
            ["name"=>"Winter Park"],
            ["name"=>"Winter Springs"],
        ]);
    }
}
